In [25]:
import pandas as pd
from datetime import datetime
from datetime import timedelta
import numpy as np


data = {
  "Acronym_athlete": ["CHI", "ARG", "COL", "SLO", "HUN", "USA", "CAN", "MEX", "ITA", "JPN", "NED", "BEL", "TPE", "NZL", "AUS", "GBR", "SGP", "HKG", "CHN", "POL", "GER", "LUX", "SUI", "FRA", "NGR", "BRA", "ISR", "AUT", "RUS", "SWE", "UKR", "SVK", "CZE", "MDA", "SRB", "UAE", "DEN", "GRE", "ALB", "SMR", "ROU", "PER", "BUL", "ESP", "POR", "CMR", "CRC", "ECU", "MAS", "BRU", "ALG", "LIE", "CRO", "PHI", "INA", "NOR", "LAT", "MAR", "NCA", "VIE", "VEN", "RSA", "GAB", "THA", "TUR", "FIN", "TUN", "LTU", "IND", "QAT", "IRL", "CYP", "MOZ", "ZIM", "LES", "MAW", "BOT", "NAM", "SWZ", "ZAM", "MRI", "GUA", "KOR", "HON", "BIH", "MAC", "BOL", "MGL", "EST", "JOR", "UGA", "BLR", "EGY", "KEN", "URU", "IRI", "ESA", "MLT", "CAY", "DOM", "ANG", "NEP", "ETH", "ISL", "AZE", "KOS", "CHA", "OMA", "LBA", "PAR", "KAZ", "CAM", "AFG", "LBN", "MAD", "PAN", "CAF", "SEN", "MON", "AND", "TKM", "MKD", "MNE", "IVB", "SUD", "PAK", "FRO", "CGO", "SOM", "GAM", "COD", "TAN", "ARM", "KGZ", "GIB", "KSA", "BRN", "RWA", "BEN", "SRI", "GRL", "CPV", "IRQ", "CUB", "BHU", "UZB", "NIG", "MDV", "GEO", "BAH", "SYR", "KUW", "MYA", "PUR", "JAM", "HAI", "BAN", "BUR", "MLI", "ISV", "GUY", "CIV", "COM", "YEM", "ERI", "COK", "ARU", "TRI", "PNG", "TOG", "swe", "BDI", "BER", "PYF", "GHA", "LAO", "PLE", "SKN", "SVE", "DAN", "NFI", "MTN", "TJK", "TKS", "SEY", "GUI", "SLE"],
  "Country_athlete": ["Chile", "Argentina", "Colombia", "Slovenia", "Hungary", "United States of America", "Canada", "Mexico", "Italy", "Japan", "Netherlands", "Belgium", "Chinese Taipei (Taiwan)", "New Zealand", "Australia", "United Kingdom", "Singapore", "Hong Kong", "China", "Poland", "Germany", "Luxembourg", "Switzerland", "France", "Nigeria", "Brazil", "Israel", "Austria", "Russia", "Sweden", "Ukraine", "Slovakia", "Czech Republic", "Moldova", "Serbia", "United Arab Emirates", "Denmark", "Greece", "Albania", "San Marino", "Romania", "Peru", "Bulgaria", "Spain", "Portugal", "Cameroon", "Costa Rica", "Ecuador", "Malaysia", "Brunei Darussalam", "Algeria", "Liechtenstein", "Croatia", "Philippines", "Indonesia", "Norway", "Latvia", "Morocco", "Nicaragua", "Vietnam", "Venezuela", "South Africa", "Gabon", "Thailand", "Turkey", "Finland", "Tunisia", "Lithuania", "India", "Qatar", "Ireland", "Cyprus", "Mozambique", "Zimbabwe", "Lesotho", "Malawi", "Botswana", "Namibia", "Eswatini", "Zambia", "Mauritius", "Guatemala", "South Korea", "Honduras", "Bosnia and Herzegovina", "Macau", "Bolivia", "Mongolia", "Estonia", "Jordan", "Uganda", "Belarus", "Egypt", "Kenya", "Uruguay", "Iran", "El Salvador", "Malta", "Cayman Islands", "Dominican Republic", "Angola", "Nepal", "Ethiopia", "Iceland", "Azerbaijan", "Kosovo", "Chad", "Oman", "Libya", "Paraguay", "Kazakhstan", "Cambodia", "Afghanistan", "Lebanon", "Madagascar", "Panama", "Central African Republic", "Senegal", "Monaco", "Andorra", "Turkmenistan", "North Macedonia", "Montenegro", "British Virgin Islands", "Sudan", "Pakistan", "Faroe Islands", "Republic of the Congo", "Somalia", "Gambia", "Democratic Republic of the Congo", "Tanzania", "Armenia", "Kyrgyzstan", "Gibraltar", "Saudi Arabia", "Brunei", "Rwanda", "Benin", "Sri Lanka", "Greenland", "Cape Verde", "Iraq", "Cuba", "Bhutan", "Uzbekistan", "Niger", "Maldives", "Georgia", "Bahamas", "Syria", "Kuwait", "Myanmar", "Puerto Rico", "Jamaica", "Haiti", "Bangladesh", "Burkina Faso", "Mali", "U.S. Virgin Islands", "Guyana", "CÃ´te dIvoire", "Comoros", "Yemen", "Eritrea", "Cook Islands", "Aruba", "Trinidad and Tobago", "Papua New Guinea", "Togo", "Sweden", "Burundi", "Bermuda", "French Polynesia", "Ghana", "Laos", "Palestine", "Saint Kitts and Nevis", "Sweden", "Denmark", "Norfolk Island", "Mauritania", "Tajikistan", "Turks and Caicos Islands", "Seychelles", "Guinea", "Sierra Leone"],
  "Continent_athlete": ["South America", "South America", "South America", "Europe", "Europe", "North America", "North America", "North America", "Europe", "Asia", "Europe", "Europe", "Asia", "Oceania", "Oceania", "Europe", "Asia", "Asia", "Asia", "Europe", "Europe", "Europe", "Europe", "Europe", "Africa", "South America", "Asia", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Asia", "Europe", "Europe", "Europe", "Europe", "Europe", "South America", "Europe", "Europe", "Europe", "Africa", "North America", "South America", "Asia", "Asia", "Africa", "Europe", "Europe", "Asia", "Asia", "Europe", "Europe", "Africa", "North America", "Asia", "South America", "Africa", "Africa", "Asia", "Asia", "Europe", "Africa", "Europe", "Asia", "Asia", "Europe", "Europe", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Central America", "Asia", "Central America", "Europe", "Asia", "South America", "Asia", "Europe", "Asia", "Africa", "Asia", "Africa", "Asia", "Africa", "South America", "Asia", "Asia", "Africa", "Central America", "Africa", "Europe", "Europe", "Asia", "Europe", "Asia", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Africa", "Asia", "Europe", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Europe", "Asia", "Europe", "Asia", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Europe", "Asia", "Asia", "Africa", "Europe", "Europe", "Europe", "Europe", "Europe", "Asia", "Europe", "Africa", "Asia", "Africa", "Africa", "Africa", "Africa", "Asia", "Asia", "Africa", "Africa", "Africa", "Asia", "Asia", "Asia", "Asia", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Europe", "Europe", "Europe", "Africa", "Asia", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa"]
}

data_event = {
  "Acronym_event": ["CHI", "ARG", "COL", "SLO", "HUN", "USA", "CAN", "MEX", "ITA", "JPN", "NED", "BEL", "TPE", "NZL", "AUS", "GBR", "SGP", "HKG", "CHN", "POL", "GER", "LUX", "SUI", "FRA", "NGR", "BRA", "ISR", "AUT", "RUS", "SWE", "UKR", "SVK", "CZE", "MDA", "SRB", "UAE", "DEN", "GRE", "ALB", "SMR", "ROU", "PER", "BUL", "ESP", "POR", "CMR", "CRC", "ECU", "MAS", "BRU", "ALG", "LIE", "CRO", "PHI", "INA", "NOR", "LAT", "MAR", "NCA", "VIE", "VEN", "RSA", "GAB", "THA", "TUR", "FIN", "TUN", "LTU", "IND", "QAT", "IRL", "CYP", "MOZ", "ZIM", "LES", "MAW", "BOT", "NAM", "SWZ", "ZAM", "MRI", "GUA", "KOR", "HON", "BIH", "MAC", "BOL", "MGL", "EST", "JOR", "UGA", "BLR", "EGY", "KEN", "URU", "IRI", "ESA", "MLT", "CAY", "DOM", "ANG", "NEP", "ETH", "ISL", "AZE", "KOS", "CHA", "OMA", "LBA", "PAR", "KAZ", "CAM", "AFG", "LBN", "MAD", "PAN", "CAF", "SEN", "MON", "AND", "TKM", "MKD", "MNE", "IVB", "SUD", "PAK", "FRO", "CGO", "SOM", "GAM", "COD", "TAN", "ARM", "KGZ", "GIB", "KSA", "BRN", "RWA", "BEN", "SRI", "GRL", "CPV", "IRQ", "CUB", "BHU", "UZB", "NIG", "MDV", "GEO", "BAH", "SYR", "KUW", "MYA", "PUR", "JAM", "HAI", "BAN", "BUR", "MLI", "ISV", "GUY", "CIV", "COM", "YEM", "ERI", "COK", "ARU", "TRI", "PNG", "TOG", "swe", "BDI", "BER", "PYF", "GHA", "LAO", "PLE", "SKN", "SVE", "DAN", "NFI", "MTN", "TJK", "TKS", "SEY", "GUI", "SLE"],
  "Country_event": ["Chile", "Argentina", "Colombia", "Slovenia", "Hungary", "United States of America", "Canada", "Mexico", "Italy", "Japan", "Netherlands", "Belgium", "Chinese Taipei (Taiwan)", "New Zealand", "Australia", "United Kingdom", "Singapore", "Hong Kong", "China", "Poland", "Germany", "Luxembourg", "Switzerland", "France", "Nigeria", "Brazil", "Israel", "Austria", "Russia", "Sweden", "Ukraine", "Slovakia", "Czech Republic", "Moldova", "Serbia", "United Arab Emirates", "Denmark", "Greece", "Albania", "San Marino", "Romania", "Peru", "Bulgaria", "Spain", "Portugal", "Cameroon", "Costa Rica", "Ecuador", "Malaysia", "Brunei Darussalam", "Algeria", "Liechtenstein", "Croatia", "Philippines", "Indonesia", "Norway", "Latvia", "Morocco", "Nicaragua", "Vietnam", "Venezuela", "South Africa", "Gabon", "Thailand", "Turkey", "Finland", "Tunisia", "Lithuania", "India", "Qatar", "Ireland", "Cyprus", "Mozambique", "Zimbabwe", "Lesotho", "Malawi", "Botswana", "Namibia", "Eswatini", "Zambia", "Mauritius", "Guatemala", "South Korea", "Honduras", "Bosnia and Herzegovina", "Macau", "Bolivia", "Mongolia", "Estonia", "Jordan", "Uganda", "Belarus", "Egypt", "Kenya", "Uruguay", "Iran", "El Salvador", "Malta", "Cayman Islands", "Dominican Republic", "Angola", "Nepal", "Ethiopia", "Iceland", "Azerbaijan", "Kosovo", "Chad", "Oman", "Libya", "Paraguay", "Kazakhstan", "Cambodia", "Afghanistan", "Lebanon", "Madagascar", "Panama", "Central African Republic", "Senegal", "Monaco", "Andorra", "Turkmenistan", "North Macedonia", "Montenegro", "British Virgin Islands", "Sudan", "Pakistan", "Faroe Islands", "Republic of the Congo", "Somalia", "Gambia", "Democratic Republic of the Congo", "Tanzania", "Armenia", "Kyrgyzstan", "Gibraltar", "Saudi Arabia", "Brunei", "Rwanda", "Benin", "Sri Lanka", "Greenland", "Cape Verde", "Iraq", "Cuba", "Bhutan", "Uzbekistan", "Niger", "Maldives", "Georgia", "Bahamas", "Syria", "Kuwait", "Myanmar", "Puerto Rico", "Jamaica", "Haiti", "Bangladesh", "Burkina Faso", "Mali", "U.S. Virgin Islands", "Guyana", "CÃ´te dIvoire", "Comoros", "Yemen", "Eritrea", "Cook Islands", "Aruba", "Trinidad and Tobago", "Papua New Guinea", "Togo", "Sweden", "Burundi", "Bermuda", "French Polynesia", "Ghana", "Laos", "Palestine", "Saint Kitts and Nevis", "Sweden", "Denmark", "Norfolk Island", "Mauritania", "Tajikistan", "Turks and Caicos Islands", "Seychelles", "Guinea", "Sierra Leone"],
  "Continent_event": ["South America", "South America", "South America", "Europe", "Europe", "North America", "North America", "North America", "Europe", "Asia", "Europe", "Europe", "Asia", "Oceania", "Oceania", "Europe", "Asia", "Asia", "Asia", "Europe", "Europe", "Europe", "Europe", "Europe", "Africa", "South America", "Asia", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Asia", "Europe", "Europe", "Europe", "Europe", "Europe", "South America", "Europe", "Europe", "Europe", "Africa", "North America", "South America", "Asia", "Asia", "Africa", "Europe", "Europe", "Asia", "Asia", "Europe", "Europe", "Africa", "North America", "Asia", "South America", "Africa", "Africa", "Asia", "Asia", "Europe", "Africa", "Europe", "Asia", "Asia", "Europe", "Europe", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Central America", "Asia", "Central America", "Europe", "Asia", "South America", "Asia", "Europe", "Asia", "Africa", "Asia", "Africa", "Asia", "Africa", "South America", "Asia", "Asia", "Africa", "Central America", "Africa", "Europe", "Europe", "Asia", "Europe", "Asia", "Europe", "Europe", "Europe", "Europe", "Europe", "Europe", "Africa", "Asia", "Europe", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Europe", "Asia", "Europe", "Asia", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Europe", "Asia", "Asia", "Africa", "Europe", "Europe", "Europe", "Europe", "Europe", "Asia", "Europe", "Africa", "Asia", "Africa", "Africa", "Africa", "Africa", "Asia", "Asia", "Africa", "Africa", "Africa", "Asia", "Asia", "Asia", "Asia", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Europe", "Europe", "Europe", "Africa", "Asia", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa", "Africa"]
}

# This dictionary is used to specify the data type for each column in the dataframe. 
# All columns are set to 'string' type.
dict_for_formats = {'Event_dates': 'string', 'Event_distance/length': 'string', 'Event_name': 'string', 'Athlete_club': 'string','Athlete_country':'string',\
                            'Athlete_gender':'string', 'Athlete_age_category': 'string', 'Athlete_performance': 'string'}

# This list contains the names of the columns that need to be converted to the data type specified in dict_for_formats.
columns_to_convert = ['Event_dates', 'Event_distance/length', 'Event_name', 'Athlete_club', 'Athlete_country', 
                      'Athlete_gender', 'Athlete_age_category', 'Athlete_performance']

# This dictionary is used to rename the columns in the dataframe. The keys are the old column names and the values are the new column names.
columns_to_rename = {'Athlete_year_of_birth': 'Age', 
                                 'Year_of_event':'Year',
                                 'Event_dates':'Date',
                                 'Event_name':'Event',
                                 'Event_distance/length':'Distance',
                                 'Athlete_performance':'Time',
                                 'Athlete_country':'Athlete Country',
                                 'Athlete_gender':'Gender'}

# This dictionary is used to replace certain patterns in the data with new patterns. 
# The keys are the old patterns and the values are the new patterns.
# For example, '(\d+)\s?mile\b' will match any string that contains a number followed by the word 'mile' (with optional whitespace in between), 
# and replace it with the same number followed by ' mi'.
replace_dict = {
    r'(\d+)\s?mile\b': r'\1 mi',
    r'(\d+)\s?k\b': r'\1 km',
    r'(\d+)\s?m\b': r'\1 mi',
    r'(\d+)\s?miles\b': r'\1 mi',
    r'\+': '',  # escape the '+' character
    '100km split': '100km',
    '4x52': '208',
    '112.km': '112'
}

# This is another dictionary used to replace certain patterns in the data with new patterns. 
# The keys are the old patterns and the values are the new patterns.
# For example, '(\d+)\s?h\b' will match any string that contains a number followed by the letter 'h' (with optional whitespace in between), 
# and replace it with the same number.
replace_dict_null = {
    r'(\d+)\s?h\b': r'\1',
    r'(\d+)\s?mi\b': r'\1',
    r'(\d+)\s?km\b': r'\1',
    '229.100.100': '229'
}

In [26]:
df = pd.read_parquet('ultramarathon.parquet')

In [27]:
# This function is designed to convert a string representing time into a standardized format.
# It takes one argument, `time_str`, which is a string representing time.
def convert_time(time_str):
    try:
        # The function first tries to parse `time_str` as a time in the format 'HH:MM:SS' (hours, minutes, and seconds).
        # The `datetime.strptime` function is used to parse the string into a datetime object.
        # The `strftime` function is then used to convert the datetime object back into a string in the 'HH:MM:SS' format.
        # If `time_str` is in the 'HH:MM:SS' format, it is returned as is, because it's already in the desired format.
        return datetime.strptime(time_str, '%H:%M:%S').strftime('%H:%M:%S')
    except ValueError:
        try:
            # If `time_str` is not in the 'HH:MM:SS' format, a `ValueError` is raised.
            # The function then catches this exception and tries to parse `time_str` as a time in the format 'MM:SS' (minutes and seconds).
            # If `time_str` is in this format, it adds '00:' to the start of the string to represent the missing hours, and then returns the result.
            return datetime.strptime(time_str, '%M:%S').strftime('00:%M:%S')
        except ValueError:
            # If `time_str` is not in the 'MM:SS' format either, another `ValueError` is raised.
            # The function catches this exception and simply returns `time_str` as is, because it's not in a format that the function knows how to handle.
            # This is a fallback mechanism to ensure that the function always returns a result, even if it's not able to convert the input string into the desired format.
            return time_str

In [28]:
# This line of code renames the columns of the DataFrame by replacing any spaces in the column names with underscores. This is done to make the column names more Pythonic and easier to work with.
df.rename(columns=lambda x: x.replace(' ', '_'), inplace=True)

# This line filters out any rows in the DataFrame where the 'Year_of_event' is less than 2000. This is done because the analysis does not require data from before the year 2000.
df = df[df['Year_of_event'] >= 2000]

# This line creates a new column 'length' in the DataFrame that contains the last two characters of the 'Event_distance/length' column. The data type of the new column is set to 'string'.
df.loc[:, 'length'] = df['Event_distance/length'].str[-2:].astype('string')

# These lines remove any rows from the DataFrame where the 'length' column contains 'd', 'h', 'en', or 'p.' and where the 'Event_distance/length' column contains 'stages', '6:40', '07:35', or 'tapp'. This is done to clean the data and remove any rows that do not conform to the expected format.
df = df[~df['length'].str.contains('d|h|en|p.')]
df = df[~df['Event_distance/length'].str.contains('stages|6:40|07:35|tapp')]

# This line changes the data type of the columns specified in 'columns_to_convert' to 'string'. This is done to ensure that the data in these columns can be manipulated as strings in the subsequent steps.
df[columns_to_convert] = df[columns_to_convert].astype('string')

# This line selects a subset of columns from the DataFrame. This is done to focus the analysis on these specific columns and reduce the complexity of the DataFrame.
df = df[['Year_of_event', 'Event_dates', 'Event_name', 'Event_distance/length', 'Athlete_performance', 'Athlete_country', 'Athlete_year_of_birth', 'Athlete_gender', 'Athlete_age_category', 'length']]

# This line renames the columns of the DataFrame according to the mapping provided in 'columns_to_rename'. This is done to make the column names more descriptive and easier to understand.
df = df.rename(columns=columns_to_rename)

# This line removes any characters before a dash in the 'Date' column. This is done to clean the data and ensure that the 'Date' column only contains date information.
df['Date'] = df['Date'].str.replace('.*.-', '', regex=True)

# This line converts the 'Date' column to datetime format with the specified format '%d.%m.%Y'. Any errors during the conversion process are handled by setting the value to NaN.
df['Date'] = pd.to_datetime(df['Date'], format='%d.%m.%Y', errors='coerce')

# This line cleans the 'Distance' column by removing trailing spaces, converting the text to lowercase, and replacing commas with periods. This is done to standardize the data in the 'Distance' column.
df['Distance'] = df['Distance'].str.rstrip().str.lower().str.replace(',', '.')

# This line replaces certain strings in the 'Distance' column according to the mapping provided in 'replace_dict'. This is done to standardize the data in the 'Distance' column.
df['Distance'] = df['Distance'].replace(replace_dict, regex=True)

# This line creates a new column 'length' in the DataFrame that contains the last two characters of the 'Distance' column. This is done to extract specific information from the 'Distance' column.
df['length'] = df['Distance'].str[-2:]

# These lines replace certain strings in the 'Time' and 'Distance' columns according to the mapping provided in 'replace_dict_null'. This is done to standardize the data in these columns.
df['Time'] = df['Time'].replace(replace_dict_null, regex=True)
df['Distance'] = df['Distance'].replace(replace_dict_null, regex=True)

# This line removes any rows from the DataFrame where the 'Time' column contains '0:00:00' or 'd'. This is done to clean the data and remove any rows that do not conform to the expected format.
df = df[~df['Time'].str.contains('0:00:00|d')]

# This line converts the 'Time' column to datetime format with the specified format '%H:%M:%S' and then extracts the time component. Any errors during the conversion process are handled by setting the value to NaN.
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S', errors='coerce').dt.time

# This line replaces the string '229.100.100' in the 'Distance' column with '229'. This is done to correct a specific error in the data.
df['Distance'] = df['Distance'].replace('229.100.100','229')

# This line converts the 'Distance' column to float, rounds the values to the nearest whole number, and then converts the column to integer. This is done to standardize the data in the 'Distance' column.
df['Distance'] = df['Distance'].astype(float).round(0).astype(int)

# This line removes any rows from the DataFrame where the 'Time' column is NaN. This is done to clean the data and remove any rows with missing time information.
df = df[df['Time'].notna()]

# This line creates a new column 'Distance(km)' in the DataFrame that contains the distance in kilometers. If the 'length' column is 'mi', the distance is converted from miles to kilometers by multiplying by 1.6.
df['Distance(km)'] = np.where(df['length'] == 'mi', df['Distance'] * 1.6, df['Distance'])

# This line converts the 'Time' column to string and applies the 'convert_time' function to each value. This is done to convert the time information to a specific format.
df['Time'] = df['Time'].astype('string').apply(convert_time)

# This line converts the 'Time' column to timedelta type. This is done to facilitate the calculation of total minutes in the next step.
df['Time'] = df['Time'].astype('timedelta64[ns]')

# This line creates a new column 'Total_minutes' in the DataFrame that contains the total minutes calculated from the 'Time' column. This is done to provide a more intuitive measure of time for the analysis.
df['Total_minutes'] = df['Time'].dt.total_seconds() / 60

# This line creates a new column 'Pace_min_per_km' in the DataFrame that contains the pace calculated as minutes per kilometer. This is done to provide a measure of the athlete's speed.
df['Pace_min_per_km'] = df['Total_minutes'] / df['Distance']

# This line rounds the values in the 'Pace_min_per_km' column to two decimal places. This is done to standardize the data in this column.
df['Pace_min_per_km']  = df['Pace_min_per_km'].round(2)

# This line converts the decimal minutes in the 'Pace_min_per_km' column to time format. This is done to provide a more intuitive measure of pace for the analysis.
df['Pace_min_per_km'] = df['Pace_min_per_km'].apply(lambda x: '{:02d}:{:02d}:{:02d}'.format(0, int(x), int((x*60) % 60), 0))

# This line converts the 'Pace_min_per_km' column to timedelta type. This is done to facilitate the filtering of the DataFrame in the next step.
df['Pace_min_per_km'] = pd.to_timedelta(df['Pace_min_per_km'])

# This line filters the DataFrame to only include rows where the 'Pace_min_per_km' is between '00:04:00' and '00:10:00' and the 'Distance(km)' is greater than or equal to 42.195. This is done to focus the analysis on specific races and athletes.
df = df[(df['Pace_min_per_km'] >= pd.to_timedelta('00:04:00')) & 
                        (df['Pace_min_per_km'] <= pd.to_timedelta('00:10:00')) &
                        (df['Distance(km)'] >= 42.195)]

# This line converts the 'Year' column to integer with 16 bits. This is done to reduce the memory usage of the DataFrame.
df['Year'] = df['Year'].astype('int16')

# This line creates a new column 'Month' in the DataFrame that contains the month extracted from the 'Date' column. This is done to provide a more granular measure of time for the analysis.
df['Month'] = df['Date'].dt.month

In [29]:
# The following line of code is commented out. If uncommented, it would drop the 'Total_minutes', 'length', and 'Distance' columns from the DataFrame.
# df = df.drop(columns=['Total_minutes', 'length', 'Distance'])

# This line converts the 'Athlete_age_category' column to a 'category' data type. The 'category' data type is useful for columns that have a limited number of unique values. It can make the DataFrame smaller in memory and can make data processing faster.
df['Athlete_age_category'] = df['Athlete_age_category'].astype('category')

# This line converts the 'Gender' column to a 'category' data type for the same reasons as above.
df['Gender'] = df['Gender'].astype('category')

# This line converts the 'Event' column to a 'category' data type for the same reasons as above.
df['Event'] = df['Event'].astype('category')

# This line fills any missing values in the 'Age' column with 0. This is done to ensure that the 'Age' column does not contain any NaN values, which could cause problems in subsequent data processing steps.
df['Age'] = df['Age'].fillna(0)

# This line converts the 'Age' column to an 'int16' data type. This is done to reduce the memory usage of the DataFrame.
df['Age'] = df['Age'].astype('int16')
df['Month'] = df['Month'].fillna(0).astype('int16')

# This line creates a new column 'Acronym_event' in the DataFrame that contains the three-letter acronym extracted from the 'Event' column. This is done using a regular expression that matches any three characters enclosed in parentheses.
df['Acronym_event'] = df['Event'].str.extract(r'\((...)\)')

# This line creates a new DataFrame 'ath_country_acr' from the 'data' object. This DataFrame contains country acronyms and names.
ath_country_acr = pd.DataFrame(data)

# This line renames the 'Athlete Country' column to 'Acronym_athlete'. This is done to make the column name more descriptive and easier to work with.
df = df.rename(columns={'Athlete Country':'Acronym_athlete'})

# This line merges the 'df' DataFrame with the 'ath_country_acr' DataFrame based on the 'Acronym_athlete' column. This is done to add the country names corresponding to the athlete country acronyms to the 'df' DataFrame.
df = pd.merge(df, ath_country_acr, on='Acronym_athlete', how='left')

# This line creates a new DataFrame 'ev_country_acr' from the 'data_event' object. This DataFrame contains event country acronyms and names.
ev_country_acr = pd.DataFrame(data_event)

# This line merges the 'df' DataFrame with the 'ev_country_acr' DataFrame based on the 'Acronym_event' column. This is done to add the country names corresponding to the event country acronyms to the 'df' DataFrame.
df = pd.merge(df, ev_country_acr, on='Acronym_event', how='left')

# Creating index for every athlete. No possibility to check if there are athletes that did more than one race so eqach athlete has unique index.
df['Athlete Index'] = range(1, len(df) + 1)

# Dropping unnecessary columns
df = df.drop(columns=['Distance','length','Acronym_event','Total_minutes', 'Acronym_athlete'])

# Sorting final dataframe
df = df[['Event','Country_event', 'Continent_event', 'Distance(km)', 'Date', 'Year','Month', 'Athlete Index', 'Age', 'Gender',
       'Athlete_age_category','Time','Pace_min_per_km','Country_athlete', 'Continent_athlete']]

df.reset_index(drop=True, inplace=True)

df.to_parquet('ultramarathons_clean.parquet', index=False)

In [30]:
df

,Event,Country_event,Continent_event,Distance(km),Date,Year,Month,Athlete Index,Age,Gender,Athlete_age_category,Time,Pace_min_per_km,Country_athlete,Continent_athlete
0,Selva Costera (CHI),Chile,South America,50.0,2018-01-06,2018,1,1,1978,M,M35,0 days 04:51:39,0 days 00:05:49,Chile,South America
1,Selva Costera (CHI),Chile,South America,50.0,2018-01-06,2018,1,2,1981,M,M35,0 days 05:15:45,0 days 00:06:19,Chile,South America
2,Selva Costera (CHI),Chile,South America,50.0,2018-01-06,2018,1,3,1987,M,M23,0 days 05:16:44,0 days 00:06:19,Chile,South America
3,Selva Costera (CHI),Chile,South America,50.0,2018-01-06,2018,1,4,1976,M,M40,0 days 05:34:13,0 days 00:06:40,Argentina,South America
4,Selva Costera (CHI),Chile,South America,50.0,2018-01-06,2018,1,5,1992,M,M23,0 days 05:54:14,0 days 00:07:04,Chile,South America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3738674,Yurrebilla Trail 56km Ultra (AUS),Australia,Oceania,56.0,2015-10-08,2015,10,3738675,1956,M,M55,0 days 09:15:26,0 days 00:09:55,Australia,Oceania
3738675,Yurrebilla Trail 56km Ultra (AUS),Australia,Oceania,56.0,2015-10-08,2015,10,3738676,1963,M,M50,0 days 09:17:11,0 days 00:09:57,Australia,Oceania
3738676,Yurrebilla Trail 56km Ultra (AUS),Australia,Oceania,56.0,2015-10-08,2015,10,3738677,1977,F,W35,0 days 09:18:46,0 days 00:09:58,Australia,Oceania
3738677,Yurrebilla Trail 56km Ultra (AUS),Australia,Oceania,56.0,2015-10-08,2015,10,3738678,1955,M,M60,0 days 09:20:06,0 days 00:10:00,Australia,Oceania
3738678,Yurrebilla Trail 56km Ultra (AUS),Australia,Oceania,56.0,2015-10-08,2015,10,3738679,1990,M,M23,0 days 09:20:15,0 days 00:10:00,Australia,Oceania